In [1]:
from pathlib import Path
import pandas as pd

DATA_PATH = Path(
    "/Users/minhtoan/SE/HocTrenLop/Trí tuệ nhân tạo/"
    "fraud-risk-screening-local-data/"
    "ibm_tabformer/card_transaction.v1.csv"
)

df_preview = pd.read_csv(
    DATA_PATH,
    nrows=5
)

print("Số dòng đang xem:", len(df_preview))
print("Số cột:", len(df_preview.columns))
print("Danh sách cột:")
print(list(df_preview.columns))

Số dòng đang xem: 5
Số cột: 15
Danh sách cột:
['User', 'Card', 'Year', 'Month', 'Day', 'Time', 'Amount', 'Use Chip', 'Merchant Name', 'Merchant City', 'Merchant State', 'Zip', 'MCC', 'Errors?', 'Is Fraud?']

In [2]:
df_preview.T

,0,1,2,3,4
User,0,0,0,0,0
Card,0,0,0,0,0
Year,2002,2002,2002,2002,2002
Month,9,9,9,9,9
Day,1,1,2,2,3
Time,06:21,06:42,06:22,17:45,06:23
Amount,$134.09,$38.48,$120.34,$128.95,$104.71
Use Chip,Swipe Transaction,Swipe Transaction,Swipe Transaction,Swipe Transaction,Swipe Transaction
Merchant Name,3527213246127876953,-727612092139916043,-727612092139916043,3414527459579106770,5817218446178736267
Merchant City,La Verne,Monterey Park,Monterey Park,Monterey Park,La Verne
Merchant State,CA,CA,CA,CA,CA
Zip,91750.0,91754.0,91754.0,91754.0,91750.0
MCC,5300,5411,5411,5651,5912
Errors?,NaN,NaN,NaN,NaN,NaN
Is Fraud?,No,No,No,No,No

In [3]:
preview = df_preview.T.copy()

preview.index.name = "Trường dữ liệu"
preview.columns = [
    "Giao dịch 1",
    "Giao dịch 2",
    "Giao dịch 3",
    "Giao dịch 4",
    "Giao dịch 5",
]

preview

,Giao dịch 1,Giao dịch 2,Giao dịch 3,Giao dịch 4,Giao dịch 5
Trường dữ liệu,,,,,
User,0,0,0,0,0
Card,0,0,0,0,0
Year,2002,2002,2002,2002,2002
Month,9,9,9,9,9
Day,1,1,2,2,3
Time,06:21,06:42,06:22,17:45,06:23
Amount,$134.09,$38.48,$120.34,$128.95,$104.71
Use Chip,Swipe Transaction,Swipe Transaction,Swipe Transaction,Swipe Transaction,Swipe Transaction
Merchant Name,3527213246127876953,-727612092139916043,-727612092139916043,3414527459579106770,5817218446178736267
Merchant City,La Verne,Monterey Park,Monterey Park,Monterey Park,La Verne
Merchant State,CA,CA,CA,CA,CA
Zip,91750.0,91754.0,91754.0,91754.0,91750.0
MCC,5300,5411,5411,5651,5912
Errors?,NaN,NaN,NaN,NaN,NaN
Is Fraud?,No,No,No,No,No